<a href="https://colab.research.google.com/github/venkat2ram/Python/blob/master/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.	Create a one dimensional array with the following values 1, 4, 3 and print the values.

In [10]:
import numpy as np
a=np.array([1,4,3])
print(a)

[1 4 3]


2.	Create a one dimensional array with the following values 1, 4, 3 and print the type of the array.

In [19]:
a=np.array([1,4,3])
print(type(a))

<class 'numpy.ndarray'>


3.	Create a two dimensional array with the following format: [(1, 2, 3), (4, 5, 6)] and print the values.

In [13]:
a=np.array([(1, 2, 3), (4, 5, 6)] )
print(a)

[[1 2 3]
 [4 5 6]]


4.	Create a two dimensional array with the following format: [(1, 2, 3), (4, 5, 6)] and print the type of the array.

In [20]:
a=np.array([(1, 2, 3), (4, 5, 6)] )
print(type(a))

<class 'numpy.ndarray'>


5.	Create a one dimensional array with the following values 1, 4, 3 and print the dimension of the array.

In [21]:
a=np.array([1,4,3])
print(a.ndim)

1


6.	For the same one dimensional array find the byte size of an each element.

In [18]:
print(a.itemsize)

8


7.	For the same one dimensional array find the data type of an each element.

In [22]:
print(a.dtype)

int64


8.	For the same one dimensional array find the size of an array.

In [24]:
a.size

3

9.	Create an array with np.zeros as 3, 3 values and print it.

In [31]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


9.	Create an array with np.zeros as 3, 3 values and print it.

In [32]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


11.	Find the shape of the array for the following values.
[(1, 2, 3), (4, 5, 6)]


In [37]:
a=np.array( [(1, 2, 3), (4, 5, 6)])
print(a.shape)

(2, 3)


12.	 Find the re shape of the array for the following values.
[(1, 2, 3), (4, 5, 6)] and reshape (4, 2) and print it.


In [48]:
a=np.array([(1, 2, 3), (4, 5, 6)])
a.reshape(4,2)


ValueError: ignored

13. Find the slice of an array for the following values.
[(1, 2, 3), (4, 5, 6)] and a [0:, 2] and print it.


In [51]:
a=np.array([(1, 2, 3), (4, 5, 6)])
a[0:,2]

array([3, 6])