<a href="https://colab.research.google.com/github/venkat2ram/Python/blob/master/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.	Create a one dimensional array with the following values 1, 4, 3 and print the values.

In [10]:
import numpy as np
a=np.array([1,4,3])
print(a)

[1 4 3]


2.	Create a one dimensional array with the following values 1, 4, 3 and print the type of the array.

In [19]:
a=np.array([1,4,3])
print(type(a))

<class 'numpy.ndarray'>


3.	Create a two dimensional array with the following format: [(1, 2, 3), (4, 5, 6)] and print the values.

In [13]:
a=np.array([(1, 2, 3), (4, 5, 6)] )
print(a)

[[1 2 3]
 [4 5 6]]


4.	Create a two dimensional array with the following format: [(1, 2, 3), (4, 5, 6)] and print the type of the array.

In [20]:
a=np.array([(1, 2, 3), (4, 5, 6)] )
print(type(a))

<class 'numpy.ndarray'>


5.	Create a one dimensional array with the following values 1, 4, 3 and print the dimension of the array.

In [21]:
a=np.array([1,4,3])
print(a.ndim)

1


6.	For the same one dimensional array find the byte size of an each element.

In [18]:
print(a.itemsize)

8


7.	For the same one dimensional array find the data type of an each element.

In [22]:
print(a.dtype)

int64


8.	For the same one dimensional array find the size of an array.

In [24]:
a.size

3

9.	Create an array with np.zeros as 3, 3 values and print it.

In [31]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


9.	Create an array with np.zeros as 3, 3 values and print it.

In [32]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


11.	Find the shape of the array for the following values.
[(1, 2, 3), (4, 5, 6)]


In [37]:
a=np.array( [(1, 2, 3), (4, 5, 6)])
print(a.shape)

(2, 3)


12.	 Find the re shape of the array for the following values.
[(1, 2, 3), (4, 5, 6)] and reshape (4, 2) and print it.


In [48]:
a=np.array([(1, 2, 3), (4, 5, 6)])
a.reshape(4,2)


ValueError: ignored

13. Find the slice of an array for the following values.
[(1, 2, 3), (4, 5, 6)] and a [0:, 2] and print it.


In [51]:
a=np.array([(1, 2, 3), (4, 5, 6)])
a[0:,2]

array([3, 6])

14. Print the linspace for the values (1, 2, 5).

In [54]:
np.linspace(1, 2, 5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

15.	 Find the sum, max, min of an array for the following values [(1,2,3),(3,4,5)].

In [56]:
a=np.array([(1,2,3),(3,4,5)])
print(a.sum(),a.min(),a.max())

18 1 5


16. Find the column wise and row wise sum of an array for the following values [(1, 2, 3), (3, 4, 5)].

In [57]:
a=np.array([(1, 2, 3), (3, 4, 5)])
print(a.sum(axis=0)) # columnwise sum
print(a.sum(axis=1))  # Rowwise sum

[4 6 8]
[ 6 12]


17. Find the transpose of an array [[1,2,3],[3,4,5],[9,6,0]] and print it.

In [59]:
a=np.array([(1,2,3),(3,4,5),(9,6,0)])
print(a.T)

[[1 3 9]
 [2 4 6]
 [3 5 0]]


18.	 Find the row wise sort and column wise sort for the following values [[1,4,2],[3,4,6],[0,-1,5]] and print it.

In [64]:
a=np.array([(1,4,2),(3,4,6),(0,-1,5)])
print(a)
print(np.sort(a,axis=0)) #Columnwise sort
print(np.sort(a,axis=1)) #Rowwise sort


[[ 1  4  2]
 [ 3  4  6]
 [ 0 -1  5]]
[[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]
[[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]


19.	 Find the horizontal split and vertical split for the following values
[[1,3,5,7,9,11],[2,4,5,8,10,12]] and print it.


In [68]:
a=np.array([(1,3,5,7,9,11),(2,4,5,8,10,12)] )
print(np.hsplit(a,2))
print(np.vsplit(a,2))

[array([[1, 3, 5],
       [2, 4, 5]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]
[array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  5,  8, 10, 12]])]


20. Find the vstack and hstack for the following values
a=np.array([(1,2,3),(3,4,5)])
b=np.array([(1,2,3),(3,4,5)]) and print it.


In [70]:
a=np.array([(1,2,3),(3,4,5)]) 
b=np.array([(1,2,3),(3,4,5)])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]
[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]
