<a href="https://colab.research.google.com/github/venkat2ram/Python/blob/master/Neural_multi_record.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
X_actual=np.array([[0],[1],[2],[3],[4],[5],[6],[7],[8],[9]])/10
y_actual=np.array([[0],[0],[0],[0],[0],[1],[1],[1],[1],[1]])
#X_actual=np.array([[2]])/10
#y_actual=np.array([[0]])

In [0]:
NumHLayers=1
NumHUnits=3

In [135]:
m,n=np.shape(X_actual)
p,s=np.shape(y_actual)
X_with_bias=np.c_[np.ones((X_actual.shape[0],1)),X_actual]
y=y_actual
hidden=np.ones((m,NumHUnits+1))
out=np.ones((p,s))
ITheta=np.ones((n+1,NumHUnits))
ETheta=np.ones((NumHUnits+1,s))
EGrad=np.ones((NumHUnits+1,s))
IGrad=np.ones((n+1,NumHUnits))
for i in range(500000):
  hidden[:,1:NumHUnits+1]=(1/(1+np.exp(-1*np.matmul(X_with_bias,ITheta))))
  out=(1/(1+np.exp(-1*np.matmul(hidden,ETheta))))
  EGrad=np.matmul(hidden.transpose(),2*(y-out)*out*(1-out))
  HGrad=(ETheta*sum(2*(y-out)*out*(1-out)))[1:NumHUnits+1]
  HTGrad=sum(hidden[:,1:NumHUnits+1]*(hidden[:,1:NumHUnits+1]*(1-hidden[:,1:NumHUnits+1])))*ITheta[1:n+1,:]
  cost=sum((y-out)**2)
  ETheta=ETheta+EGrad
  ITheta=ITheta+HTGrad*0.001
  if(i%100000==0):
    print(cost,EGrad,out)

[4.65471634] [[-0.32284844]
 [-0.24665763]
 [-0.24665763]
 [-0.24665763]] [[0.96057666]
 [0.96270114]
 [0.96461955]
 [0.96634974]
 [0.96790866]
 [0.96931226]
 [0.97057532]
 [0.97171152]
 [0.97273338]
 [0.97365233]]
[4.29381966] [[0.60006082]
 [0.60006952]
 [0.60006952]
 [0.60006952]] [[0.07014682]
 [0.07325484]
 [0.07481627]
 [0.07558864]
 [0.07596782]
 [0.07615329]
 [0.07624385]
 [0.07628803]
 [0.07630957]
 [0.07632007]]
[4.06041597] [[0.74414039]
 [0.74415044]
 [0.74415044]
 [0.74415044]] [[0.10040268]
 [0.1027901 ]
 [0.10388846]
 [0.10438953]
 [0.10461725]
 [0.10472056]
 [0.1047674 ]
 [0.10478862]
 [0.10479824]
 [0.10480259]]
[2.49621593] [[0.16017558]
 [0.16026925]
 [0.16026925]
 [0.16026925]] [[0.46125941]
 [0.4659037 ]
 [0.46792214]
 [0.46879879]
 [0.46917944]
 [0.46934469]
 [0.46941644]
 [0.46944758]
 [0.46946111]
 [0.46946698]]
[2.65348097] [[0.59971389]
 [0.59976422]
 [0.59976422]
 [0.59976422]] [[0.36737722]
 [0.37075658]
 [0.37218398]
 [0.37278591]
 [0.37303956]
 [0.37314643

In [129]:
ITheta[1:n+1,:]*HTGrad

array([[1.23214901, 1.23214901, 1.23214901]])

In [133]:
HTGrad

array([[0.05279146, 0.05279146, 0.05279146]])

In [119]:
hidden[:,1:NumHUnits+1]

array([[0.73105858, 0.73105858, 0.73105858],
       [0.75026011, 0.75026011, 0.75026011],
       [0.76852478, 0.76852478, 0.76852478],
       [0.78583498, 0.78583498, 0.78583498],
       [0.80218389, 0.80218389, 0.80218389],
       [0.81757448, 0.81757448, 0.81757448],
       [0.83201839, 0.83201839, 0.83201839],
       [0.84553473, 0.84553473, 0.84553473],
       [0.85814894, 0.85814894, 0.85814894],
       [0.86989153, 0.86989153, 0.86989153]])