<a href="https://colab.research.google.com/github/venkat2ram/Python/blob/master/Neural_multi_record.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
X_actual=np.array([[0],[1],[2],[3],[4],[5],[6],[7],[8],[9]])/10
y_actual=np.array([[0],[0],[0],[0],[0],[1],[1],[1],[1],[1]])
#X_actual=np.array([[2]])/10
#y_actual=np.array([[0]])

In [0]:
NumHLayers=1
NumHUnits=3

In [85]:
m,n=np.shape(X_actual)
p,s=np.shape(y_actual)
X_with_bias=np.c_[np.ones((X_actual.shape[0],1)),X_actual]
y=y_actual
hidden=np.ones((m,NumHUnits+1))
out=np.ones((p,s))
#ITheta=np.ones((n+1,NumHUnits))
ITheta=np.random.rand(n+1,NumHUnits)
#ETheta=np.ones((NumHUnits+1,s))
ETheta=np.random.rand(NumHUnits+1,s)
EGrad=np.ones((NumHUnits+1,s))
IGrad=np.ones((n+1,NumHUnits))
for i in range(700000):
  hidden[:,1:NumHUnits+1]=(1/(1+np.exp(-1*np.matmul(X_with_bias,ITheta))))
  out=(1/(1+np.exp(-1*np.matmul(hidden,ETheta))))
  EGrad=np.matmul(hidden.transpose(),2*(y-out)*out*(1-out))
  #HGrad=(ETheta*sum(2*(y-out)*out*(1-out)))[1:NumHUnits+1]
  HGrad=np.sum(np.matmul(ETheta[1:NumHUnits+1],(2*(y-out)*out*(1-out)).transpose()),axis=1)
  HTGrad=np.matmul(X_with_bias.transpose(),hidden[:,1:NumHUnits+1]*HGrad)
  #HTGrad=sum(hidden[:,1:NumHUnits+1]*(hidden[:,1:NumHUnits+1]*(1-hidden[:,1:NumHUnits+1])))*ITheta[1:n+1,:]
  cost=sum((y-out)**2)
  ETheta=ETheta+EGrad*0.01
  ITheta=ITheta+HTGrad*0.01
  if(i%100000==0):
    print(cost,HGrad,out)

[3.25069438] [-0.17872614 -0.79070135 -0.75201313] [[0.77334899]
 [0.77596189]
 [0.77848778]
 [0.78092647]
 [0.78327818]
 [0.78554354]
 [0.78772353]
 [0.78981948]
 [0.79183296]
 [0.79376583]]
[1.04632881] [-0.27096835  0.09814558 -0.27611567] [[0.14111996]
 [0.2118119 ]
 [0.29656204]
 [0.38879965]
 [0.48069425]
 [0.56566983]
 [0.63982109]
 [0.70189313]
 [0.75245639]
 [0.79299413]]
[0.88755203] [-0.25624253  0.05887054 -0.21274545] [[0.09167234]
 [0.16096858]
 [0.25482627]
 [0.36494774]
 [0.47786232]
 [0.58124922]
 [0.66822881]
 [0.73740395]
 [0.79065302]
 [0.83101934]]
[0.81992552] [-0.24561351  0.04597632 -0.19288855] [[0.07166819]
 [0.13754121]
 [0.23355303]
 [0.35171115]
 [0.47539093]
 [0.58832898]
 [0.68159462]
 [0.75381185]
 [0.80780618]
 [0.84760171]]
[0.77798057] [-0.23844366  0.03912147 -0.18318866] [[0.05998447]
 [0.12268731]
 [0.2191489 ]
 [0.34225087]
 [0.47327078]
 [0.59282624]
 [0.6903251 ]
 [0.76443954]
 [0.81875484]
 [0.85802969]]
[0.74811464] [-0.23313861  0.03471627 -0

In [63]:
np.random.rand(NumHUnits+1,s)

array([[0.17091614],
       [0.83686957],
       [0.48632481],
       [0.05814245]])

In [66]:
ETheta

array([[-3.24172598e+01],
       [-2.54990952e-02],
       [-9.01257361e+00],
       [ 6.20821362e+01]])

In [72]:
HTGrad

array([[-2.94977399e-05, -6.92301236e-06, -2.98922761e-05],
       [-8.42691443e-06, -2.11022005e-06, -9.57897376e-06]])

In [73]:
EGrad

array([[ 2.00875873e-05],
       [-4.16867599e-03],
       [-2.57404140e-03],
       [-3.79401247e-03]])

In [74]:
ITheta

array([[-4.7710567 , -5.22052559, -4.78870332],
       [-2.14958941, -1.86520293, -1.64767294]])