<a href="https://colab.research.google.com/github/venkat2ram/Python/blob/master/Neural_rough.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np



In [0]:
X_actual=np.array([[2]])/10
y_actual=np.array([[0]])

In [0]:
NumHLayers=1
NumHUnits=1

In [0]:
X=np.c_[np.ones((X_actual.shape[0],1)),X_actual]
y=y_actual

In [128]:
m,n=np.shape(X_actual)
p,s=np.shape(y_actual)
X_with_bias=np.c_[np.ones((X_actual.shape[0],1)),X_actual]
y=y_actual
hidden=np.ones((1,2))
out=np.ones((1,1))
ITheta=np.ones((2,1))
ETheta=np.ones((2,1))
EGrad=np.ones((2,1))
HGrad=np.ones((2,1))
hidden[0,1]=(1/(1+np.exp(-1*np.matmul(X_with_bias,ITheta))))
out[0,0]=(1/(1+np.exp(-1*np.matmul(hidden,ETheta))))
cost=(y-out)**2
print(cost,out,EGrad)
for i in range(100000):
  EGrad=np.matmul(hidden.transpose(),2*(y-out)*out*(1-out))
  HGrad=2*(y-out)*out*(1-out)*ETheta[1,0]
  IGrad=np.matmul(X_with_bias.transpose(), HGrad*(hidden[0,1]*(1-hidden[0,1])))
  ETheta=ETheta+EGrad
  ITheta=ITheta+IGrad
  hidden[0,1]=(1/(1+np.exp(-1*np.matmul(X_with_bias,ITheta))))
  out[0,0]=(1/(1+np.exp(-1*np.matmul(hidden,ETheta))))
  cost=(y-out)**2
  if(i%5000==0):
    print(cost,out,EGrad)

[[0.72978427]] [[0.85427412]] [[1.]
 [1.]]
[[0.64965093]] [[0.80600926]] [[-0.21269691]
 [-0.16346285]]
[[2.89058243e-05]] [[0.00537641]] [[-5.75126472e-05]
 [-4.79520965e-05]]
[[1.41783238e-05]] [[0.00376541]] [[-2.82527646e-05]
 [-2.38105677e-05]]
[[9.36008704e-06]] [[0.00305943]] [[-1.86641721e-05]
 [-1.58248154e-05]]
[[6.97523528e-06]] [[0.00264107]] [[-1.39143362e-05]
 [-1.18468506e-05]]
[[5.55408871e-06]] [[0.00235671]] [[-1.10824505e-05]
 [-9.46568724e-06]]
[[4.61149474e-06]] [[0.00214744]] [[-9.20349616e-06]
 [-7.88088350e-06]]
[[3.94093844e-06]] [[0.00198518]] [[-7.86645875e-06]
 [-6.75030217e-06]]
[[3.43969794e-06]] [[0.00185464]] [[-6.86681174e-06]
 [-5.90320702e-06]]
[[3.05094449e-06]] [[0.0017467]] [[-6.09136852e-06]
 [-5.24488787e-06]]
[[2.74070012e-06]] [[0.00165551]] [[-5.47243704e-06]
 [-4.71858808e-06]]
[[2.48740727e-06]] [[0.00157715]] [[-4.96706030e-06]
 [-4.28822646e-06]]
[[2.27673175e-06]] [[0.00150888]] [[-4.54666986e-06]
 [-3.92976966e-06]]
[[2.09877285e-06]] [[

In [94]:
out,y,cost,EGrad,ETheta,IGrad,ITheta,hidden

(array([[0.86145916]]),
 array([[1]]),
 array([[0.01919356]]),
 array([[0.03628279],
        [0.02788422]]),
 array([[1.03628279],
        [1.02788422]]),
 array([[0.00645451],
        [0.0012909 ]]),
 array([[1.00645451],
        [1.0012909 ]]),
 array([[1.        , 0.76971678]]))

In [124]:
X_with_bias.shape

(2, 2)

In [80]:
X_with_bias

array([[1. , 0.2]])

In [0]:
ETheta=ETheta+Egrad

In [123]:
hidden[]

array([[1., 1.]])