<a href="https://colab.research.google.com/github/venkat2ram/Python/blob/master/Neural_rough.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np



In [0]:
X_actual=np.array([2]).reshape(1,-1)/10
y_actual=np.array([[1]])

In [0]:
NumHLayers=1
NumHUnits=1

In [0]:
X=np.c_[np.ones((X_actual.shape[0],1)),X_actual]
y=y_actual

In [0]:
m,n=np.shape(X_actual)
p,s=np.shape(y_actual)
X_with_bias=np.c_[np.ones((X_actual.shape[0],1)),X_actual]
y=y_actual
hidden=np.ones((1,2))
out=np.ones((1,1))
ITheta=np.ones((2,1))
ETheta=np.ones((2,1))
EGrad=np.ones((2,1))
HGrad=np.ones((2,1))
hidden[0,1]=(1/(1+np.exp(-1*np.matmul(X_with_bias,ITheta))))
out[0,0]=(1/(1+np.exp(-1*np.matmul(hidden,ETheta))))
cost=(y-out)**2
EGrad=np.matmul(hidden.transpose(),2*(y-out)*out*(1-out))
HGrad=2*(y-out)*out*(1-out)*ETheta[1,0]
IGrad=np.matmul(X_with_bias.transpose(), HGrad*(hidden[0,1]*(1-hidden[0,1])))
ETheta=ETheta+EGrad

out[0,0]=(1/(1+np.exp(-1*np.matmul(hidden,ETheta))))
cost=(y-out)**2

In [76]:
out,y,cost,EGrad,ETheta

(array([[0.86131287]]),
 array([[1]]),
 array([[0.01923412]]),
 array([[0.03628279],
        [0.02788422]]),
 array([[1.03628279],
        [1.02788422]]))

In [70]:
np.matmul(hidden.transpose(),2*(y-out)*out*(1-out))

array([[0.03628279],
       [0.02788422]])

In [80]:
X_with_bias

array([[1. , 0.2]])

In [0]:
ETheta=ETheta+Egrad

In [74]:
ETheta

array([[3.],
       [3.]])