<a href="https://colab.research.google.com/github/venkat2ram/Python/blob/master/Python_data_analatycs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy:**

In [9]:
import numpy as np
a=np.array([(1,2,3),(4,5,6)])
print(a[:,1]

array([2, 5])

Columnwise sum

In [12]:
print(a.min(),a.max(),a.sum(),a.min(axis=0),a.max(axis=1),a.sum(axis=0),a.sum(axis=1))

1 6 21 [1 2 3] [3 6] [5 7 9] [ 6 15]


Square root and standard deviation:

In [14]:
a.std()

1.707825127659933

Sorting

In [17]:
b=([(4,2,5),(6,3,7)])
np.sort(b)

array([[2, 4, 5],
       [3, 6, 7]])

Column wise sorting.

In [19]:
b=([(4,2,5),(6,3,1)])
np.sort(b,axis=0)

array([[4, 2, 1],
       [6, 3, 5]])

rowwise sorting.

In [21]:
b=([(4,2,5),(6,3,1)])
np.sort(b,axis=1) # This works same as np.sort(b)

array([[2, 4, 5],
       [1, 3, 6]])

Exponentials and logarithms:

In [22]:
c=([(1,2,3)])
print(np.exp(c),np.log(c),np.log10(c))

[[ 2.71828183  7.3890561  20.08553692]] [[0.         0.69314718 1.09861229]] [[0.         0.30103    0.47712125]]


Convert all columns and rows into single column.

In [25]:
a.ravel() #This converts array into tuple.

array([1, 2, 3, 4, 5, 6])

**Matplotlib**

In [33]:
import matplotlib.pyplot as plt
x=np.arange(1,np.pi,3)
x

dtype('float64')